[Variables]

HomePage=www.google.com

IconSpacingH=205.4
IconSpacingV=177.25

Player=iTunes

SystemCommand=C:\Windows\System32\shutdown /a

WPImage=

;----------------------- Colors ------------------------
White=255,255,255
Blue=0,78,255
Red=230,0,0

Grey=255, 255, 255, 80
DarkGrey=255, 255, 255, 40

Yellow=255,255,0
Red=255,0,0,255
LightBlue = 150,160,255
Green=0,255,0
Black=0,0,0
ButtonLight=58,142,145
ButtonDark=35,78,79
Orange=255,125,0


;----------------------- Applications -----------------------
App1Name=Microsoft Terminal Services Client (RDP)
App1Path=mstsc.exe
App1Icon=mstsc.png
;----------------------------
App2Name=
App2Path=
App2Icon=
;----------------------------
App3Name=SCCM Remote Control Viewer
App3Path=C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin\i386\CmRcViewer.exe
App3Icon=RCV.png
;----------------------------
App4Name=pcA QuickConnect
App4Path=C:\Program Files (x86)\Symantec\pcAnywhere\PCAQuickConnect.exe
App4Icon=pca.png
;----------------------------
App5Name=
App5Path=
App5Icon=
;----------------------------
App6Name=Remote Desktop Connection Manager
App6Path=C:\Program Files (x86)\Remote Desktop Connection Manager\RDCMan.exe
App6Icon=RDCM.png
;----------------------------
App7Name=
App7Path=
App7Icon=
;----------------------------
App8Name=Sabre
App8Path=C:\Program Files (x86)\Csapi\Sv32.exe
App8Icon=Sabre.png
;----------------------------
App9Name=
App9Path=
App9Icon=
;----------------------------
App10Name=Windows XP Mode
App10Path=C:\Users\wnowacki\Virtual Machines\Windows XP Mode.vmcx
App10Icon=xp.png
;----------------------------
App11Name=
App11Path=
App11Icon=
;----------------------------
App12Name=SCCM Console
App12Path=C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin\Microsoft.ConfigurationManagement.exe
App12Icon=SCCM.png
;----------------------------
App13Name=
App13Path=
App13Icon=
;----------------------------
App14Name=
App14Path=
App14Icon=
;----------------------------
App15Name=Altiris Central
App15Path=http://phx-52n-altnsc/Altiris/Resource/ResourcePicker.aspx?&ConsoleGuid=1b22db4e-a898-443f-9b99-855b1653d3f5
App15Icon=Altiris.png
;----------------------------
App16Name=Altiris East
App16Path=http://phx-52n-altnse/Altiris/Resource/ResourcePicker.aspx?&ConsoleGuid=1b22db4e-a898-443f-9b99-855b1653d3f5
App16Icon=Altiris.png
;----------------------------
App17Name=Altiris West
App17Path=http://phx-52n-altnsw/Altiris/Resource/ResourcePicker.aspx?&ConsoleGuid=1b22db4e-a898-443f-9b99-855b1653d3f5
App17Icon=Altiris.png
;----------------------------
App18Name=PC Lookup
App18Path=\\PIT-OCC-FPS01\Public\WNowacki\PCLookup\PCLookup.exe
App18Icon=pclookup.png
;----------------------------
App19Name=
App19Path=
App19Icon=
;----------------------------
App20Name=SPE Monitor
App20Path=C:\Altiris_DS\SPEMonitor\SPEMonitor.exe
App20Icon=spemon.png
;----------------------------
App21Name=
App21Path=
App21Icon=
;----------------------------
App22Name=Password Helper
App22Path=\\pit-occ-fps01\Public\Wnowacki\_Apps\PasswordHelper.exe
App22Icon=PwdHelper.png
;----------------------------
App23Name=Photoshop 8
App23Path=C:\Altiris_DS\Portables\Portable Photoshop 8 CS\Portable_PS_8.exe
App23Icon=Photoshop.png
;----------------------------
App24Name=
App24Path=
App24Icon=
;----------------------------
App25Name=Chrome
App25Path=Chrome.exe
App25Icon=Chrome.png
;----------------------------
App26Name=Internet Explorer
App26Path=iexplore.exe
App26Icon=IE.png
;----------------------------
App27Name=
App27Path=
App27Icon=
;----------------------------
App28Name=Network Scanner
App28Path=C:\Altiris_DS\NetScan.exe
App28Icon=NetScan.png
